### ISSUE TITLE
Emacs support

### ISSUE THREAD

**Issue by joaogui1** [mlochbaum/BQN#10]
Any plans on adding emacs support? (I sadly don't program in elisp :/)

**Comment by mlochbaum** [comment]
I also don't know any elisp, but I can look into it. There are a few Emacs APL plugins floating around, and I know the author of [this one](https://github.com/lokedhs/gnu-apl-mode), so I have someone to ask if I need help.

**Comment by joaogui1** [comment]
Thank you very much!

**Comment by mlochbaum** [comment]
I've now adapted the keymap code from gnu-apl-mode. I'll do syntax highlighting and indentation later but wanted to make sure this part works on someone else's Emacs. Placing the following code (with the appropriate path) in your configuration should give you access. Then you'll be able to enable the backslash keyboard, or use super in BQN files—see the comments [here](../blob/master/editors/emacs/bqn-mode.el).

    (add-to-list 'load-path "/path/to/BQN/editors/emacs")
    (require 'bqn-mode)

**Comment by joaogui1** [comment]
It's working here :D

**Comment by sternenseemann** [comment]
Any chance we could get it the emacs support into MELPA? That would probably make installing it a lot more convenient for a lot of ppl.

**Comment by mlochbaum** [comment]
I think it'll be easier for an Emacs user to submit it (they might be more likely to maintain it as well). Not being familiar with Emacs I find a lot of the tooling hard to work with. I also haven't been able to get indentation working even though BQN's rules are very simple (indent on open bracket and restore indentation on close).

**Comment by sternenseemann** [comment]
MELPA should be quite low maintenance since they update the packages from git automatically, I think, but probably makes sense if an actual users does adds the package if they allow that, true.

**Comment by AndersonTorres** [comment]
What would be better in this regard: maintaining `bqn-mode` outside or inside BQN source tree?

**Comment by mlochbaum** [comment]
MELPA [says](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org) "Keep each package in its own SCM (e.g., git) repository" so I think it has to go outside (and it's probably better organization anyway). Whoever hosts the repo needs to commit to responding to issues and PRs. I can do that if necessary but would prefer not to.

**Comment by AndersonTorres** [comment]
What would be the bureaucracy involved in this?

I am planning on port BQN+CBQN to [Nixpkgs](https://github.com/NixOS/nixpkgs/), but I need to wait the [Hydra](https://hydra.nixos.org/) CI/CD complete a full cycle before uploading new modifications. When everything becomes OK, I can try the port more seriously.

**Comment by mlochbaum** [comment]
FYI there's an [open PR](https://github.com/NixOS/nixpkgs/pull/135665) for CBQN in Nix, and [bqn-mode](https://github.com/NixOS/nixpkgs/pull/136712) has been accepted. I don't know why the CBQN one hasn't been touched or whether that's typical.

**Comment by sternenseemann** [comment]
> FYI there's an [open PR](https://github.com/NixOS/nixpkgs/pull/135665) for CBQN in Nix, and [bqn-mode](https://github.com/NixOS/nixpkgs/pull/136712) has been accepted. I don't know why the CBQN one hasn't been touched or whether that's typical.

Probably a non-trivial package not everyone knows about / is interested in. I'll try to get this in soon (was hesitant so far, since unreleased software built from git tends to bitrot if there's no big interest in it).

**Comment by AndersonTorres** [comment]
I didn't notice this open PR until now. Good to know, I will take it as base for my experimentations!

Indeed it is way common. Sometimes by lack of manpower many PRs are forgotten.

(Indeed, was this bqn-mode expression that incited me to search BQN, lol)

---------

About the issue at hand: I volunteer to maintain bqn-mode.

**Comment by AndersonTorres** [comment]
@mlochbaum and anyone interested in this thread:

As promised (?), I have created a dedicated repository for all the code **and** commits related to bqn-mode.

Here is it: https://github.com/AndersonTorres/bqn-mode

**Comment by mlochbaum** [comment]
I've removed the bqn-mode folder from this repository; issues should go to that one now.
