### ISSUE TITLE
try.html gives an error on the new predicate guards

### ISSUE THREAD

**Issue by AlexDikelsky** [mlochbaum/BQN#30]
If I try to run [this code](https://mlochbaum.github.io/BQN/try.html#code=ewogKDEgPSAyKSA/IDMKfQ==), I get the error message `s is undefined`.

**Comment by mlochbaum** [comment]
This *is* a runtime error because the predicate fails, indicating that it should go to the next body, but there are none left. Error formatting is failing here; I'll have to figure out why tomorrow morning.

**Comment by mlochbaum** [comment]
It actually failed to throw an error and returned `undefined`, which isn't a valid BQN value. I'd missed it because predicates made a previously unreachable part of the compiled JS reachable.
