### ISSUE TITLE
Link to tacit.html page not found

### ISSUE THREAD

**Issue by dmaahs2017** [mlochbaum/BQN#36]
This document links to a page that does not exist: https://mlochbaum.github.io/BQN/doc/train.html

The broken link is: https://mlochbaum.github.io/BQN/doc/tacit.html

![image](https://user-images.githubusercontent.com/18738072/139605104-23d48bdd-24fa-49d5-b492-a1c4952cb091.png)

**Comment by mlochbaum** [comment]
I put the link in expecting to write it quickly but never finished it. It'll be there eventually.
