### ISSUE TITLE
Explain the use of `under ​⌾` primitive in tutorial/variable.md

### ISSUE THREAD

**Issue by RedEmberCat** [mlochbaum/BQN#38]
This is the paragraph where that primitive first appears  in the tutorial:

> So let's break this down. The 2-modifier Under (⌾) has two operands: the left one, -⟜1, subtracts one, and the right one, 2⊸⊑ uses a function we haven't seen before. It uses the right operand to pick out part of its argument, then the left one acts on that part only, and the entire argument, with the necessary modifications, is returned.

**Comment by mlochbaum** [comment]
What's the complaint here? The last sentence in that paragraph is a general description of what `⌾` does. It's a difficult primitive to digest right away, so the tutorial continues with more and simpler examples. Is there something wrong about this presentation?
