### ISSUE TITLE
Allow Emojii variable names

### ISSUE THREAD

**Issue by vegabook** [mlochbaum/BQN#48]
![image](https://user-images.githubusercontent.com/3780883/146296070-fb4a8404-8c45-4e82-bd0b-5070a2cd0205.png)

Why can't I use the flying saucer Emojii, in the language for flying saucers!?

I want to be able to sprinkle my hieroglyphic BQN code, with emojii. ASCII begone! `camelCase` getouttahere. 

This would be properly fun (even if discouraged 'officially'). 

Can it be done? You're using UTF-16 already, right? Most terminals, VIM, etc, support it no problem. According to [this](https://www.smashingmagazine.com/2016/11/character-sets-encoding-emoji/), they're encodable using UTF-16. 

You know you want to! (or at least, I certainly do!)

Only slightly more seriously: 
![image](https://user-images.githubusercontent.com/3780883/146297515-1adc2b45-bfda-4faa-ab5b-874a5c43f1f9.png)

So at the very least, Unicode support for variable names? 

Python doesn't support emojii variable names however, and...although I'm not sure this is good for the argument, but Javascript does. More interestingly, so does Swift: 

![image](https://user-images.githubusercontent.com/3780883/146299005-96d654de-dd56-4da3-84da-58dd959fbca9.png)

**Comment by mlochbaum** [comment]
I *do* want to, in fact. But every letter in a BQN variable name needs to have both an upper- and lowercase form in order to decide its role. Emoji and arbitrary Unicode is out for this reason. I'm not against adding other alphabets, but the rules for casing in non-latin alphabets can get complicated and I don't think it makes sense to expend the effort to untangle these, and risk making a bad choice we'll have to undo or work around in the future.

The feature BQN does (JS) or will (CBQN) have is the ability to define custom primitives, which can use any character. [This](https://mlochbaum.github.io/BQN/try.html#code=YiDihpAg4oCiUmVCUU4ge3ByaW1pdGl2ZXPih5DigKJwcmltaXRpdmVz4oi+4p+oJ/Cfm7gn4oC/KDHijL3ijL0p4p+pfQpCICLwn5u44oaVOSI=) is a simple space-based example (no problem with BQN's Unicode handling: in fact I had to expend some effort to make sure that instead of Javascript's UTF-16 each atom is an entire code point, more like UTF-32). As in non-extended BQN, primitives have to be functions or modifiers, and have a fixed value and role across a single program. Mathematical symbols like `∫` that you might want to put in a variable are likely to be used as primitives in this way, which is another reason to avoid adding too many Unicode possibilities.

**Comment by vegabook** [comment]
Right I do get it now. Sorry just (re)starting my journey on BQN and thought this would be fun, more than anything else, and the fun aspect, even if it has limitations, is catered for by primitives. I had seen glancing through your tutorials the distinction between functions and their [upper/lower]case forms, so I get it.

**Comment by vegabook** [comment]
So just giving this a bit more thought overnight, I have to say that I think it's more than just a bit of fun, somehow, over time, to enable new symbols to be usable within BQN. 

After all, it's about notation as a tool of thought, after all, and I personally, would absolutely love to write a bond market (and possibly crypto market) statistical analysis DSL using BQN, but be able to have some of my analysis algorithms bound to new symbols. I think this could be very powerful, as opposed to having this mixture of traditional ascii for any variable or function in BQN, and only the core language being able to leverage concise symbology. This is especially the case that you seem to be borrowing quite a lot from LISP/SCHEME which of course, encourage DSLs. 

As a backgrounder, I am an accomplished vector programmer, but in R first, and Numpy second, but I really like the idea of terse symbology and array programming first, with the hope that one day BQN will in a "mechanically sympathetic" way, be able to target SIMD and GPU architectures, as the VM progresses. 

I have lots of experience in numerical computing having spent a decade writing and maintaining a host of bond market relative value tools which use vectorization extensively. 

Anyway, just a little motivation! I understand of course that it's not just like flicking a switch, but my view is that the effort would be well rewarded.

**Comment by mlochbaum** [comment]
We've just [finished adding](https://github.com/dzaima/CBQN/pull/14) support for primitive extension in CBQN (by coincidence, I started just before you filed this issue), and it's now documented [here](https://mlochbaum.github.io/BQN/doc/rebqn.html). I have a few ideas about how we might make it easier to specify that a file should be evaluated with a particular extension; for now you'd want to write a separate script like at the bottom of [bqn.bqn](https://github.com/mlochbaum/BQN/blob/fc2687ffc8dcb8117bb957bea6b4e7bbdb45ca71/bqn.bqn#L58-L65) using a `•ReBQN` result in place of `BQN`, and use that as your executable.

We're making good progress on SIMD as well: [Singeli](https://github.com/mlochbaum/Singeli) is our DSL for it, and it can be [used](https://github.com/dzaima/CBQN/blob/master/src/singeli/src/cmp.singeli) for comparison functions already. If you somehow find yourself with free time on your hands, having another programmer who can write SIMD algorithms would be a great help, and I'd be happy to get you up to speed with our system and do what I can to make Singeli more usable.

**Comment by vegabook** [comment]
I hesitate to say that I am able to be of great help at the VM level _yet_, because I obviously first thoroughly need to learn BQN, and of course, I'm an applied mathematician first and system programmer second (despite my computer science degree all those years ago). But sure, as I progress, and if I feel comfortable "trading below with the big boys" like you, Dzaima, etc, I will try and help. Certainly I love the project.

**Comment by mlochbaum** [comment]
"I obviously first thoroughly need to learn BQN": You don't actually! What CBQN needs now is optimized primitive implementations, and each of these is really its own world not depending on others. So you can learn them one at a time, and in fact working on the implementation is a good way to learn a primitive ([thread](https://chat.stackexchange.com/transcript/message/56120084#56120084); [other thread](https://chat.stackexchange.com/transcript/52405?m=55418984#55418984)). It's a time sink for sure though.

Good luck with BQN! You're not on Matrix already, right? If so I have no idea which one's your account.
