### ISSUE TITLE
Confusing Take error in REPL

### ISSUE THREAD

**Issue by ajc2** [mlochbaum/BQN#52]
In the online REPL, this code produces an error that just looks like nonsense.
```
3↑2‿2⥊↕4
×: Arguments must be numbers
```
CBQN produces this output:
```
   3↑2‿2⥊↕4
┌─     
╵ 0 1  
  2 3  
  0 0  
      ┘
```

**Comment by mlochbaum** [comment]
I had an error in the fast-path code for Take with an atom on the left. You can see this because `⟨3⟩↑2‿2⥊↕4` works and there should never be a difference between `n↑` and `⟨n⟩↑`. Take is such a difficult primitive…
