### ISSUE TITLE
:bug: Grade Up/Down Broken

### ISSUE THREAD

**Issue by codereport** [mlochbaum/BQN#54]
The following BQN code `⍋1‿2‿5‿2‿3` return `⟨ 0 1 3 4 2 ⟩` when it should return `⟨ 0 1 4 2 3 ⟩`

Permalink: https://mlochbaum.github.io/BQN/try.html#code=4o2LMeKAvzLigL814oC/MuKAvzM=

**Comment by codereport** [comment]
Was I supposed to post this issue to CBQN?

**Comment by dzaima** [comment]
It's returning the correct thing - an index into the original array for each result element. `⍋⊸⊏ 1‿2‿5‿2‿3` is how you'd use it to sort the array

**Comment by mlochbaum** [comment]
The JS version has nothing to do with CBQN, so if you run it online and get the same results you should file here. However, I can confirm that this is the expected result. The [Grade documentation](https://mlochbaum.github.io/BQN/doc/order.html#grade) discusses dzaima's `⍋⍋` suggestion in the "Ordinals" section. You might also check against APL, which has the same definition (adjusting for `⎕IO`).

**Comment by codereport** [comment]
:facepalm: I actually did cross reference with APL but I used a different sequence `⍋1 2 5 3 2`. Clearly I haven't used `Grade`s enough to know their behaviour. 

Sorry!
