### ISSUE TITLE
The example of `Switch` produces an error

### ISSUE THREAD

**Issue by shnarazk** [mlochbaum/BQN#66]
Sorry for a noob question.
I tried `Switch` described on [Control flow in BQN](https://mlochbaum.github.io/BQN/doc/control.html#switch-case) on [REPL](https://mlochbaum.github.io/BQN/try.html#code=U3dpdGNoIOKGkCB7Y+KGkOKKkfCdlakg4ouEIG3igL9h4oaQPMuY4o2J4oiY4oC/MuKlijHihpPwnZWpIOKLhCAo4oqRYeKKkEMp4pe2bUB9CnZhbHVlIOKGkCAiZG91YmxlIgp2IOKGkCAzMwpTd2l0Y2gg4p+odmFsdWUKICAiaW5jcmVtZW50IiDii4Qge/CdlaTii4QgdivihqkxfQogICJkZWNyZW1lbnQiIOKLhCB78J2VpOKLhCB2LeKGqTF9CiAgImRvdWJsZSIgICAg4ouEIHvwnZWk4ouEIHbDl+KGqTJ9CiAgImhhbHZlIiAgICAg4ouEIHvwnZWk4ouEIHbDt+KGqTJ9CuKfqQo=) and CBQN:

```apl
Switch ← {c←⊑𝕩 ⋄ m‿a←<˘⍉∘‿2⥊1↓𝕩 ⋄ (⊑a⊐C)◶m@}
value ← "double"
v ← 33
Switch ⟨value
  "increment" ⋄ {𝕤⋄ v+↩1}
  "decrement" ⋄ {𝕤⋄ v-↩1}
  "double"    ⋄ {𝕤⋄ v×↩2}
  "halve"     ⋄ {𝕤⋄ v÷↩2}
⟩
```

and got the following error:

```
𝕨⊑𝕩: Index out of range

Switch ← {c←⊑𝕩 ⋄ m‿a←<˘⍉∘‿2⥊1↓𝕩 ⋄ (⊑a⊐C)◶m@}
                                  ^^^^^^^^

Switch ⟨value
^^^^^^
```

So something is wrong. I found this one seems to work ([REPL](https://mlochbaum.github.io/BQN/try.html#code=U3dpdGNoIOKGkCB7Y+KGkOKKkfCdlakg4ouEIG3igL9h4oaQPMuY4o2J4oiY4oC/MuKlijHihpPwnZWpIOKLhCAo4oqR4oiYKG3iirjiipAp4oiYPEMp4pe2YUB9CnZhbHVlIOKGkCAiIgp2YWx1ZSDihqkgImRvdWJsZSIKdiDihpAgMzMKU3dpdGNoIOKfqHZhbHVlCiAgImluY3JlbWVudCIg4ouEIHvwnZWk4ouEIHYr4oapMX0KICAiZGVjcmVtZW50IiDii4Qge/CdlaTii4Qgdi3ihqkxfQogICJkb3VibGUiICAgIOKLhCB78J2VpOKLhCB2w5fihqkyfQogICJoYWx2ZSIgICAgIOKLhCB78J2VpOKLhCB2w7fihqkyfQrin6kKCg==)):

```apl
Switch ← {c←⊑𝕩 ⋄ m‿a←<˘⍉∘‿2⥊1↓𝕩 ⋄ (⊑∘(m⊸⊐)∘<C)◶a@}
```
Is this OK?

**Comment by mlochbaum** [comment]
[Search function depth](https://mlochbaum.github.io/BQN/commentary/problems.html#search-function-depth) strikes again. From that page, `m⊸⊐⌾<C` is a little nicer. Thanks for testing this!
