### ISSUE TITLE
3 | ¯4 results in 2 in BQNPAD and the online REPL

### ISSUE THREAD

**Issue by ionse** [mlochbaum/BQN#79]
I feel the result should be 1, unless I'm missing something...?

I did test with the left argument set to 1, 2, 4, 5, 6, 7, and 8, with correct results.

**Comment by mlochbaum** [comment]
Well, `¯4+2×3` is 2 so I believe you're arithmetic's just off. And here's Python:
```
>>> -4 % 3
2
```
In case there's any confusion about C-like modular division (although your comment about other arguments wouldn't be consistent with that), BQN always returns a non-negative result for positive `𝕨`.

**Comment by ionse** [comment]
Many thanks for getting back to me so fast.

I'm new to BQN and you are correct, I got my wires crossed!

Chris

------- Original Message -------
