### ISSUE TITLE
Tutorial: 1-Modifier example

### ISSUE THREAD

**Issue by m3m0ry** [mlochbaum/BQN#80]
The example [here](https://github.com/mlochbaum/BQN/blame/master/tutorial/expression.md#L160) would be easier to grasp with other numbers. `4^2 == 2^4` which doesn't immediately show the intent of the `Swap`, because the output is the same, with or without the `Swap`. Could you take `3` or `5` instead of `4`?

**Comment by mlochbaum** [comment]
Good point, thanks for bringing it up! I've changed it to 5.
