### ISSUE TITLE
Typo in bqnpad ceiling operator

### ISSUE THREAD

**Issue by willmendil** [mlochbaum/BQN#88]
![image](https://github.com/mlochbaum/BQN/assets/8661949/d8b279ca-bd1e-437d-b660-ae04e1eea61f)

hi just to say that there's a typo on bqnpad, don't know if this is the correct repo, nor how to fix it. so here's the fyi

**Comment by mlochbaum** [comment]
The repo is https://github.com/mechanize-systems/bqnpad, so please file there.
