### ISSUE TITLE
Unfinished documentation 

### ISSUE THREAD

**Issue by walseb** [mlochbaum/BQN#89]
Hello! 

The documentation string here under "Insert With Initial" appears unfinished. 

https://mlochbaum.github.io/BQN/help/insert.html

Thanks!

**Comment by mlochbaum** [comment]
Thanks for reporting! I didn't write this part, but I don't think there's anything else to be said about what `𝕨` does, and the corresponding Fold and Scan sections don't have extra text. So I've just removed the paragraph.
