### ISSUE TITLE
List tutorial shows wrong binding for primitive each

### ISSUE THREAD

**Issue by hollmmax** [mlochbaum/BQN#9]
The modifier each `¨` is shown as `\1` in the list tutorial, when both kakoune and REPL bindings use `\2`.

**Comment by hollmmax** [comment]
So I wanted to take a look at this myself, but the binding tables are the only thing not in the markdown and are instead generated by BQN...

**Comment by mlochbaum** [comment]
Thank you! Even if the tables were done in markdown, you'd still have to regenerate the docs. If you're using Unix, it should be pretty easy to install [dzaima/BQN](https://github.com/dzaima/BQN/), add the script shown [here](https://mlochbaum.github.io/BQN/running.html#dzaimareference-bqn) somewhere in your path as `dbqn`, and then run `./gendocs` from the main repository (or `./gendocs tutorial/list.md` to do just one a little quicker). Not that you have to, of course—for an issue like this, pulling a PR is hardly any easier than just changing it myself.
