### ISSUE TITLE
Mention VS Code extension in Editor Support

### ISSUE THREAD

**Issue by sohang3112** [mlochbaum/BQN#91]
In [Editor Support](https://mlochbaum.github.io/BQN/editors/index.html) page, mention the [BQN extension for VS Code](https://marketplace.visualstudio.com/items?itemName=razetime.bqn-language).

**Comment by mlochbaum** [comment]
It has a dedicated section [here](https://mlochbaum.github.io/BQN/editors/index.html#vs-code).
